### PR TITLE
License

### PR DESCRIPTION
**Pull request by richo**
There are lots of GPLv3 references in various source files. Is that a blanket license for the project?

Is it worth adding LICENSE to the root?

### CODE REVIEW

**Comment by haxwithaxe** [comment]
@richo, @virtadpt has worked for some of the less well informed parts of the US government and thus while still under contract obligations to them he is trying to keep them happy.

I would prefer an MIT license (i'm a fan of public domain but until it's legally clear that one can forfit copyrights to a work to a nonentity MIT is as close as it gets) but it's not that important to me which FOSS licence we use.

I think a LICENSE file would be a good idea as long as we say it applies only where another license isn't specified for other parts of the project. we are doing a lot of borrowing so it would be good to not imply squashing other projects' licenses.

**Comment by richo** [comment]
Cool. I added a PR to this issue.
- My legalese isn't great. I have no idea what the legal status of the clause about 3rd party projects would be.
- I included the two authors I've spoken to, but I have no idea how you like to be referred to in matters of IP ownership, or your contact addresses.

Thus, at best it needs tweaking before it's worth rebasing on master.

**Comment by Sitwon** [comment]
I spoke with @virtadpt about this and for CYA reasons with his employer he feels most comfortable with licensing his contributions as GPLv3. I think we should change that first paragraph to read something like: "Unless otherwise specified, the works in this repository are copyright $Byzantium_Team and covered under the MIT License." And then make sure that all the 3rd-party code in the repository is properly marked to indicate the appropriate author(s) and license(s). This would allow @virtadpt to continue using GPLv3 for the parts that he is working on without jeopardizing his employment, and it should also allow others to contribute to other parts of the system under their preferred license.

We should probably also start a AUTHORS or CONTRIBUTORS file to record the people who have contributed to this project.

**Comment by haxwithaxe** [comment]
using GPLv3 for CYA

**Pull request closed without merging**
