### PR TITLE
French translation for the portal

### PR DESCRIPTION
**Pull request by raphael-proust**
According to http://drwho.virtadpt.net/archive/2012/04/08/sailing-to-byzantium-v02a translations will be needed eventually.

Cheers,

### CODE REVIEW

**Comment by Sitwon** [comment]
Merci beaucoup!

**Comment by virtadpt** [comment]
Thank you so much!

**Comment by virtadpt** [comment]
Would you be interested in translating the control panel's HTML into French as well?  It wouldn't be in the style of the captive portal daemon but using i18n strings.  We're not there yet but we're going to start it soon.

**Comment by raphael-proust** [comment]
Sure.

I'll also try to find someone to proof-read and correct misspellings and grammar errors…

**Comment by virtadpt** [comment]
Great!  When I've got more time I'll describe what we've got so far in this commit comment.

**Pull request merged**
